## Querying ERCOT Pricing Data

In [2]:
import gridstatusio

gridstatusio.__version__

'0.13.0'

## Setting up the API client

First, we need to set up the GridStatusClient by providing our API key. You can either set the API key using the `GRIDSTATUS_API_KEY` environment variable or pass it to the constructor directly.

In [3]:
client = gridstatusio.GridStatusClient()
client

GridStatusClient(host=https://api.gridstatus.io/v1)

## Day Ahead Settlement Point Prices

In [5]:
# Get all settlement points in ERCOT
df_dam = client.get_dataset(
    dataset="ercot_spp_day_ahead_hourly",
    start="2024-10-01",
    end="2024-10-02",
    timezone="market",
)

df_dam.head(10)

2025-07-28 08:50:50 - INFO - Fetching Page 1...
2025-07-28 08:50:50 - INFO - GET https://api.gridstatus.io/v1/datasets/ercot_spp_day_ahead_hourly/query
2025-07-28 08:50:50 - INFO - Params: {'start_time': Timestamp('2024-10-01 00:00:00'), 'end_time': Timestamp('2024-10-02 00:00:00'), 'publish_time_start': None, 'publish_time_end': None, 'limit': None, 'page': 1, 'page_size': None, 'resample_frequency': None, 'resample_by': None, 'resample_function': None, 'publish_time': None, 'timezone': 'market', 'cursor': '', 'filter_column': None, 'filter_value': None, 'filter_operator': '=', 'return_format': 'json', 'json_schema': 'array-of-arrays'}
2025-07-28 08:50:51 - INFO - Done in 1.11 seconds.
2025-07-28 08:50:51 - INFO - Total number of rows: 22320

,interval_start_local,interval_start_utc,interval_end_local,interval_end_utc,location,location_type,market,spp
0,2024-10-01 00:00:00-05:00,2024-10-01 05:00:00+00:00,2024-10-01 01:00:00-05:00,2024-10-01 06:00:00+00:00,7RNCHSLR_ALL,Resource Node,DAY_AHEAD_HOURLY,20.84
1,2024-10-01 00:00:00-05:00,2024-10-01 05:00:00+00:00,2024-10-01 01:00:00-05:00,2024-10-01 06:00:00+00:00,ADL_RN,Resource Node,DAY_AHEAD_HOURLY,20.73
2,2024-10-01 00:00:00-05:00,2024-10-01 05:00:00+00:00,2024-10-01 01:00:00-05:00,2024-10-01 06:00:00+00:00,AEEC,Resource Node,DAY_AHEAD_HOURLY,19.29
3,2024-10-01 00:00:00-05:00,2024-10-01 05:00:00+00:00,2024-10-01 01:00:00-05:00,2024-10-01 06:00:00+00:00,AE_RN,Resource Node,DAY_AHEAD_HOURLY,20.71
4,2024-10-01 00:00:00-05:00,2024-10-01 05:00:00+00:00,2024-10-01 01:00:00-05:00,2024-10-01 06:00:00+00:00,AGUAYO_UNIT1,Resource Node,DAY_AHEAD_HOURLY,22.67
5,2024-10-01 00:00:00-05:00,2024-10-01 05:00:00+00:00,2024-10-01 01:00:00-05:00,2024-10-01 06:00:00+00:00,AJAXWIND_RN,Resource Node,DAY_AHEAD_HOURLY,20.35
6,2024-10-01 00:00:00-05:00,2024-10-01 05:00:00+00:00,2024-10-01 01:00:00-05:00,2024-10-01 06:00:00+00:00,ALGOD_ALL_RN,Resource Node,DAY_AHEAD_HOURLY,20.39
7,2024-10-01 00:00:00-05:00,2024-10-01 05:00:00+00:00,2024-10-01 01:00:00-05:00,2024-10-01 06:00:00+00:00,ALP_BESS_RN,Resource Node,DAY_AHEAD_HOURLY,30.99
8,2024-10-01 00:00:00-05:00,2024-10-01 05:00:00+00:00,2024-10-01 01:00:00-05:00,2024-10-01 06:00:00+00:00,ALVIN_RN,Resource Node,DAY_AHEAD_HOURLY,20.70
9,2024-10-01 00:00:00-05:00,2024-10-01 05:00:00+00:00,2024-10-01 01:00:00-05:00,2024-10-01 06:00:00+00:00,AMADEUS_ALL,Resource Node,DAY_AHEAD_HOURLY,20.70

In [7]:
# Get just the trading hubs
df_dam_hubs = client.get_dataset(
    dataset="ercot_spp_day_ahead_hourly",
    start="2024-10-01",
    end="2024-10-02",
    filter_column="location_type",
    filter_value="Trading Hub",
    timezone="market",
)

df_dam_hubs.head(10)

2025-07-28 08:51:08 - INFO - Fetching Page 1...
2025-07-28 08:51:08 - INFO - GET https://api.gridstatus.io/v1/datasets/ercot_spp_day_ahead_hourly/query
2025-07-28 08:51:08 - INFO - Params: {'start_time': Timestamp('2024-10-01 00:00:00'), 'end_time': Timestamp('2024-10-02 00:00:00'), 'publish_time_start': None, 'publish_time_end': None, 'limit': None, 'page': 1, 'page_size': None, 'resample_frequency': None, 'resample_by': None, 'resample_function': None, 'publish_time': None, 'timezone': 'market', 'cursor': '', 'filter_column': 'location_type', 'filter_value': 'Trading Hub', 'filter_operator': '=', 'return_format': 'json', 'json_schema': 'array-of-arrays'}
2025-07-28 08:51:08 - INFO - Done in 0.13 seconds.
2025-07-28 08:51:08 - INFO - Total number of rows: 168

,interval_start_local,interval_start_utc,interval_end_local,interval_end_utc,location,location_type,market,spp
0,2024-10-01 00:00:00-05:00,2024-10-01 05:00:00+00:00,2024-10-01 01:00:00-05:00,2024-10-01 06:00:00+00:00,HB_BUSAVG,Trading Hub,DAY_AHEAD_HOURLY,21.04
1,2024-10-01 00:00:00-05:00,2024-10-01 05:00:00+00:00,2024-10-01 01:00:00-05:00,2024-10-01 06:00:00+00:00,HB_HOUSTON,Trading Hub,DAY_AHEAD_HOURLY,20.70
2,2024-10-01 00:00:00-05:00,2024-10-01 05:00:00+00:00,2024-10-01 01:00:00-05:00,2024-10-01 06:00:00+00:00,HB_HUBAVG,Trading Hub,DAY_AHEAD_HOURLY,21.41
3,2024-10-01 00:00:00-05:00,2024-10-01 05:00:00+00:00,2024-10-01 01:00:00-05:00,2024-10-01 06:00:00+00:00,HB_NORTH,Trading Hub,DAY_AHEAD_HOURLY,20.65
4,2024-10-01 00:00:00-05:00,2024-10-01 05:00:00+00:00,2024-10-01 01:00:00-05:00,2024-10-01 06:00:00+00:00,HB_PAN,Trading Hub,DAY_AHEAD_HOURLY,20.04
5,2024-10-01 00:00:00-05:00,2024-10-01 05:00:00+00:00,2024-10-01 01:00:00-05:00,2024-10-01 06:00:00+00:00,HB_SOUTH,Trading Hub,DAY_AHEAD_HOURLY,20.88
6,2024-10-01 00:00:00-05:00,2024-10-01 05:00:00+00:00,2024-10-01 01:00:00-05:00,2024-10-01 06:00:00+00:00,HB_WEST,Trading Hub,DAY_AHEAD_HOURLY,23.41
7,2024-10-01 01:00:00-05:00,2024-10-01 06:00:00+00:00,2024-10-01 02:00:00-05:00,2024-10-01 07:00:00+00:00,HB_BUSAVG,Trading Hub,DAY_AHEAD_HOURLY,20.80
8,2024-10-01 01:00:00-05:00,2024-10-01 06:00:00+00:00,2024-10-01 02:00:00-05:00,2024-10-01 07:00:00+00:00,HB_HOUSTON,Trading Hub,DAY_AHEAD_HOURLY,20.59
9,2024-10-01 01:00:00-05:00,2024-10-01 06:00:00+00:00,2024-10-01 02:00:00-05:00,2024-10-01 07:00:00+00:00,HB_HUBAVG,Trading Hub,DAY_AHEAD_HOURLY,21.08

In [8]:
# Get a specific trading hub or any other location
df_dam_hubs = client.get_dataset(
    dataset="ercot_spp_day_ahead_hourly",
    start="2024-10-01",
    end="2024-10-02",
    filter_column="location",
    filter_value="HB_HOUSTON",
    timezone="US/Central",
)

df_dam_hubs.head(10)

2025-07-28 08:51:29 - INFO - Fetching Page 1...
2025-07-28 08:51:29 - INFO - GET https://api.gridstatus.io/v1/datasets/ercot_spp_day_ahead_hourly/query
2025-07-28 08:51:29 - INFO - Params: {'start_time': Timestamp('2024-10-01 00:00:00'), 'end_time': Timestamp('2024-10-02 00:00:00'), 'publish_time_start': None, 'publish_time_end': None, 'limit': None, 'page': 1, 'page_size': None, 'resample_frequency': None, 'resample_by': None, 'resample_function': None, 'publish_time': None, 'timezone': 'US/Central', 'cursor': '', 'filter_column': 'location', 'filter_value': 'HB_HOUSTON', 'filter_operator': '=', 'return_format': 'json', 'json_schema': 'array-of-arrays'}
2025-07-28 08:51:29 - INFO - Done in 0.19 seconds.
2025-07-28 08:51:29 - INFO - Total number of rows: 24

,interval_start_local,interval_start_utc,interval_end_local,interval_end_utc,location,location_type,market,spp
0,2024-10-01 00:00:00-05:00,2024-10-01 05:00:00+00:00,2024-10-01 01:00:00-05:00,2024-10-01 06:00:00+00:00,HB_HOUSTON,Trading Hub,DAY_AHEAD_HOURLY,20.70
1,2024-10-01 01:00:00-05:00,2024-10-01 06:00:00+00:00,2024-10-01 02:00:00-05:00,2024-10-01 07:00:00+00:00,HB_HOUSTON,Trading Hub,DAY_AHEAD_HOURLY,20.59
2,2024-10-01 02:00:00-05:00,2024-10-01 07:00:00+00:00,2024-10-01 03:00:00-05:00,2024-10-01 08:00:00+00:00,HB_HOUSTON,Trading Hub,DAY_AHEAD_HOURLY,19.20
3,2024-10-01 03:00:00-05:00,2024-10-01 08:00:00+00:00,2024-10-01 04:00:00-05:00,2024-10-01 09:00:00+00:00,HB_HOUSTON,Trading Hub,DAY_AHEAD_HOURLY,19.93
4,2024-10-01 04:00:00-05:00,2024-10-01 09:00:00+00:00,2024-10-01 05:00:00-05:00,2024-10-01 10:00:00+00:00,HB_HOUSTON,Trading Hub,DAY_AHEAD_HOURLY,20.84
5,2024-10-01 05:00:00-05:00,2024-10-01 10:00:00+00:00,2024-10-01 06:00:00-05:00,2024-10-01 11:00:00+00:00,HB_HOUSTON,Trading Hub,DAY_AHEAD_HOURLY,22.09
6,2024-10-01 06:00:00-05:00,2024-10-01 11:00:00+00:00,2024-10-01 07:00:00-05:00,2024-10-01 12:00:00+00:00,HB_HOUSTON,Trading Hub,DAY_AHEAD_HOURLY,28.75
7,2024-10-01 07:00:00-05:00,2024-10-01 12:00:00+00:00,2024-10-01 08:00:00-05:00,2024-10-01 13:00:00+00:00,HB_HOUSTON,Trading Hub,DAY_AHEAD_HOURLY,23.98
8,2024-10-01 08:00:00-05:00,2024-10-01 13:00:00+00:00,2024-10-01 09:00:00-05:00,2024-10-01 14:00:00+00:00,HB_HOUSTON,Trading Hub,DAY_AHEAD_HOURLY,17.29
9,2024-10-01 09:00:00-05:00,2024-10-01 14:00:00+00:00,2024-10-01 10:00:00-05:00,2024-10-01 15:00:00+00:00,HB_HOUSTON,Trading Hub,DAY_AHEAD_HOURLY,12.03

## Real Time Settlement Point Prices
We can do all the same things above for other LMP or Settlement Point Price datasets as well.

In [9]:
df_rt = client.get_dataset(
    dataset="ercot_spp_real_time_15_min",
    start="2024-10-01",
    end="2024-10-02",
    filter_column="location",
    filter_value="HB_HOUSTON",
    timezone="US/Central",
)
df_rt.head(10)

2025-07-28 08:51:55 - INFO - Fetching Page 1...
2025-07-28 08:51:55 - INFO - GET https://api.gridstatus.io/v1/datasets/ercot_spp_real_time_15_min/query
2025-07-28 08:51:55 - INFO - Params: {'start_time': Timestamp('2024-10-01 00:00:00'), 'end_time': Timestamp('2024-10-02 00:00:00'), 'publish_time_start': None, 'publish_time_end': None, 'limit': None, 'page': 1, 'page_size': None, 'resample_frequency': None, 'resample_by': None, 'resample_function': None, 'publish_time': None, 'timezone': 'US/Central', 'cursor': '', 'filter_column': 'location', 'filter_value': 'HB_HOUSTON', 'filter_operator': '=', 'return_format': 'json', 'json_schema': 'array-of-arrays'}
2025-07-28 08:51:56 - INFO - Done in 0.2 seconds.
2025-07-28 08:51:56 - INFO - Total number of rows: 96

,interval_start_local,interval_start_utc,interval_end_local,interval_end_utc,location,location_type,market,spp
0,2024-10-01 00:00:00-05:00,2024-10-01 05:00:00+00:00,2024-10-01 00:15:00-05:00,2024-10-01 05:15:00+00:00,HB_HOUSTON,Trading Hub,REAL_TIME_15_MIN,24.16
1,2024-10-01 00:15:00-05:00,2024-10-01 05:15:00+00:00,2024-10-01 00:30:00-05:00,2024-10-01 05:30:00+00:00,HB_HOUSTON,Trading Hub,REAL_TIME_15_MIN,23.64
2,2024-10-01 00:30:00-05:00,2024-10-01 05:30:00+00:00,2024-10-01 00:45:00-05:00,2024-10-01 05:45:00+00:00,HB_HOUSTON,Trading Hub,REAL_TIME_15_MIN,22.44
3,2024-10-01 00:45:00-05:00,2024-10-01 05:45:00+00:00,2024-10-01 01:00:00-05:00,2024-10-01 06:00:00+00:00,HB_HOUSTON,Trading Hub,REAL_TIME_15_MIN,22.67
4,2024-10-01 01:00:00-05:00,2024-10-01 06:00:00+00:00,2024-10-01 01:15:00-05:00,2024-10-01 06:15:00+00:00,HB_HOUSTON,Trading Hub,REAL_TIME_15_MIN,22.18
5,2024-10-01 01:15:00-05:00,2024-10-01 06:15:00+00:00,2024-10-01 01:30:00-05:00,2024-10-01 06:30:00+00:00,HB_HOUSTON,Trading Hub,REAL_TIME_15_MIN,22.36
6,2024-10-01 01:30:00-05:00,2024-10-01 06:30:00+00:00,2024-10-01 01:45:00-05:00,2024-10-01 06:45:00+00:00,HB_HOUSTON,Trading Hub,REAL_TIME_15_MIN,22.28
7,2024-10-01 01:45:00-05:00,2024-10-01 06:45:00+00:00,2024-10-01 02:00:00-05:00,2024-10-01 07:00:00+00:00,HB_HOUSTON,Trading Hub,REAL_TIME_15_MIN,22.14
8,2024-10-01 02:00:00-05:00,2024-10-01 07:00:00+00:00,2024-10-01 02:15:00-05:00,2024-10-01 07:15:00+00:00,HB_HOUSTON,Trading Hub,REAL_TIME_15_MIN,23.12
9,2024-10-01 02:15:00-05:00,2024-10-01 07:15:00+00:00,2024-10-01 02:30:00-05:00,2024-10-01 07:30:00+00:00,HB_HOUSTON,Trading Hub,REAL_TIME_15_MIN,23.78

## Real Time LMPs (from SCED)
Get the real time LMPs for a specific settlement point

In [10]:
df_rt_lmp = client.get_dataset(
    dataset="ercot_lmp_by_settlement_point",
    start="2024-10-01",
    end="2024-10-02",
    filter_column="location",
    filter_value="BATCAVE_RN",
    timezone="market",
)
df_rt_lmp.head(10)

2025-07-28 08:52:33 - INFO - Fetching Page 1...
2025-07-28 08:52:33 - INFO - GET https://api.gridstatus.io/v1/datasets/ercot_lmp_by_settlement_point/query
2025-07-28 08:52:33 - INFO - Params: {'start_time': Timestamp('2024-10-01 00:00:00'), 'end_time': Timestamp('2024-10-02 00:00:00'), 'publish_time_start': None, 'publish_time_end': None, 'limit': None, 'page': 1, 'page_size': None, 'resample_frequency': None, 'resample_by': None, 'resample_function': None, 'publish_time': None, 'timezone': 'market', 'cursor': '', 'filter_column': 'location', 'filter_value': 'BATCAVE_RN', 'filter_operator': '=', 'return_format': 'json', 'json_schema': 'array-of-arrays'}
2025-07-28 08:52:34 - INFO - Done in 0.55 seconds.
2025-07-28 08:52:34 - INFO - Total number of rows: 288

,interval_start_local,interval_start_utc,interval_end_local,interval_end_utc,sced_timestamp_local,sced_timestamp_utc,market,location,location_type,lmp
0,2024-10-01 00:00:00-05:00,2024-10-01 05:00:00+00:00,2024-10-01 00:05:00-05:00,2024-10-01 05:05:00+00:00,2024-10-01 00:00:14-05:00,2024-10-01 05:00:14+00:00,REAL_TIME_SCED,BATCAVE_RN,Resource Node,15.91
1,2024-10-01 00:05:00-05:00,2024-10-01 05:05:00+00:00,2024-10-01 00:10:00-05:00,2024-10-01 05:10:00+00:00,2024-10-01 00:05:13-05:00,2024-10-01 05:05:13+00:00,REAL_TIME_SCED,BATCAVE_RN,Resource Node,22.11
2,2024-10-01 00:10:00-05:00,2024-10-01 05:10:00+00:00,2024-10-01 00:15:00-05:00,2024-10-01 05:15:00+00:00,2024-10-01 00:10:15-05:00,2024-10-01 05:10:15+00:00,REAL_TIME_SCED,BATCAVE_RN,Resource Node,23.48
3,2024-10-01 00:15:00-05:00,2024-10-01 05:15:00+00:00,2024-10-01 00:20:00-05:00,2024-10-01 05:20:00+00:00,2024-10-01 00:15:13-05:00,2024-10-01 05:15:13+00:00,REAL_TIME_SCED,BATCAVE_RN,Resource Node,22.12
4,2024-10-01 00:20:00-05:00,2024-10-01 05:20:00+00:00,2024-10-01 00:25:00-05:00,2024-10-01 05:25:00+00:00,2024-10-01 00:20:12-05:00,2024-10-01 05:20:12+00:00,REAL_TIME_SCED,BATCAVE_RN,Resource Node,23.16
5,2024-10-01 00:25:00-05:00,2024-10-01 05:25:00+00:00,2024-10-01 00:30:00-05:00,2024-10-01 05:30:00+00:00,2024-10-01 00:25:12-05:00,2024-10-01 05:25:12+00:00,REAL_TIME_SCED,BATCAVE_RN,Resource Node,19.86
6,2024-10-01 00:30:00-05:00,2024-10-01 05:30:00+00:00,2024-10-01 00:35:00-05:00,2024-10-01 05:35:00+00:00,2024-10-01 00:30:13-05:00,2024-10-01 05:30:13+00:00,REAL_TIME_SCED,BATCAVE_RN,Resource Node,19.69
7,2024-10-01 00:35:00-05:00,2024-10-01 05:35:00+00:00,2024-10-01 00:40:00-05:00,2024-10-01 05:40:00+00:00,2024-10-01 00:35:12-05:00,2024-10-01 05:35:12+00:00,REAL_TIME_SCED,BATCAVE_RN,Resource Node,18.84
8,2024-10-01 00:40:00-05:00,2024-10-01 05:40:00+00:00,2024-10-01 00:45:00-05:00,2024-10-01 05:45:00+00:00,2024-10-01 00:40:14-05:00,2024-10-01 05:40:14+00:00,REAL_TIME_SCED,BATCAVE_RN,Resource Node,21.91
9,2024-10-01 00:45:00-05:00,2024-10-01 05:45:00+00:00,2024-10-01 00:50:00-05:00,2024-10-01 05:50:00+00:00,2024-10-01 00:45:13-05:00,2024-10-01 05:45:13+00:00,REAL_TIME_SCED,BATCAVE_RN,Resource Node,22.03

Other relevant pricing datasets include:

* Real-time LMPs by bus: https://www.gridstatus.io/datasets/ercot_lmp_by_bus
* Day-ahead LMPs by bus: https://www.gridstatus.io/datasets/ercot_lmp_by_bus_dam
* SCED system lambda: https://www.gridstatus.io/datasets/ercot_sced_system_lambda

See full list of datasets at https://www.gridstatus.io/datasets

## Ancillary Services Prices
Get the ancillary services prices for ERCOT

In [ ]:
df_rt_lmp = client.get_dataset(
    dataset="ercot_as_prices",
    start="2024-10-01",
    end="2024-10-02",
    timezone="market",
)
df_rt_lmp.head(10)

Fetching Page 1...Done in 0.75 seconds.

Total number of rows: 24

,interval_start_local,interval_start_utc,interval_end_local,interval_end_utc,market,non_spinning_reserves,regulation_down,regulation_up,responsive_reserves,ercot_contingency_reserve_service
0,2024-10-01 00:00:00-05:00,2024-10-01 05:00:00+00:00,2024-10-01 01:00:00-05:00,2024-10-01 06:00:00+00:00,DAM,0.0900,1.2500,1.3200,0.7800,0.0500
1,2024-10-01 01:00:00-05:00,2024-10-01 06:00:00+00:00,2024-10-01 02:00:00-05:00,2024-10-01 07:00:00+00:00,DAM,0.0900,0.7900,1.0000,0.7500,0.0500
2,2024-10-01 02:00:00-05:00,2024-10-01 07:00:00+00:00,2024-10-01 03:00:00-05:00,2024-10-01 08:00:00+00:00,DAM,0.0700,0.6500,0.7500,0.7500,0.0400
3,2024-10-01 03:00:00-05:00,2024-10-01 08:00:00+00:00,2024-10-01 04:00:00-05:00,2024-10-01 09:00:00+00:00,DAM,0.0700,0.4900,0.7500,0.7500,0.0400
4,2024-10-01 04:00:00-05:00,2024-10-01 09:00:00+00:00,2024-10-01 05:00:00-05:00,2024-10-01 10:00:00+00:00,DAM,0.0700,0.4900,1.0000,0.7500,0.0500
5,2024-10-01 05:00:00-05:00,2024-10-01 10:00:00+00:00,2024-10-01 06:00:00-05:00,2024-10-01 11:00:00+00:00,DAM,0.0600,0.9400,1.4000,0.7500,0.0500
6,2024-10-01 06:00:00-05:00,2024-10-01 11:00:00+00:00,2024-10-01 07:00:00-05:00,2024-10-01 12:00:00+00:00,DAM,1.0700,0.7900,1.3200,0.8000,0.0500
7,2024-10-01 07:00:00-05:00,2024-10-01 12:00:00+00:00,2024-10-01 08:00:00-05:00,2024-10-01 13:00:00+00:00,DAM,1.0100,1.2500,0.8000,0.8000,0.0600
8,2024-10-01 08:00:00-05:00,2024-10-01 13:00:00+00:00,2024-10-01 09:00:00-05:00,2024-10-01 14:00:00+00:00,DAM,1.0100,5.0000,1.2400,0.7800,0.7800
9,2024-10-01 09:00:00-05:00,2024-10-01 14:00:00+00:00,2024-10-01 10:00:00-05:00,2024-10-01 15:00:00+00:00,DAM,1.0100,1.5000,1.2300,0.8000,0.8000

## Find possible `location` values

In [11]:
# We can query for one SPP interval and extract the unique locations from that
interval_data = client.get_dataset(
    dataset="ercot_spp_day_ahead_hourly",
    start="2024-10-01 00:00:00",
    end="2024-10-01 01:00:00",
    timezone="US/Central",
)

locations = interval_data[["location", "location_type"]].drop_duplicates()
locations

2025-07-28 08:54:06 - INFO - Fetching Page 1...
2025-07-28 08:54:06 - INFO - GET https://api.gridstatus.io/v1/datasets/ercot_spp_day_ahead_hourly/query
2025-07-28 08:54:06 - INFO - Params: {'start_time': Timestamp('2024-10-01 00:00:00'), 'end_time': Timestamp('2024-10-01 01:00:00'), 'publish_time_start': None, 'publish_time_end': None, 'limit': None, 'page': 1, 'page_size': None, 'resample_frequency': None, 'resample_by': None, 'resample_function': None, 'publish_time': None, 'timezone': 'US/Central', 'cursor': '', 'filter_column': None, 'filter_value': None, 'filter_operator': '=', 'return_format': 'json', 'json_schema': 'array-of-arrays'}
2025-07-28 08:54:06 - INFO - Done in 0.21 seconds.
2025-07-28 08:54:06 - INFO - Total number of rows: 930

         location  location_type
0    7RNCHSLR_ALL  Resource Node
1          ADL_RN  Resource Node
2            AEEC  Resource Node
3           AE_RN  Resource Node
4    AGUAYO_UNIT1  Resource Node
..            ...            ...
925  W_PECO_UNIT1  Resource Node
926  WRSBES_BESS1  Resource Node
927      X443ESRN  Resource Node
928   YNG_WND_ALL  Resource Node
929  ZIER_SLR_ALL  Resource Node

[930 rows x 2 columns]

In [13]:
# Return the unique locations types
locations["location_type"].value_counts()

location_type
Resource Node       911
Load Zone             8
Trading Hub           7
Load Zone DC Tie      4
Name: count, dtype: int64

In [14]:
# Return all the trading hubs
locations[locations["location_type"] == "Trading Hub"]

       location location_type
383   HB_BUSAVG   Trading Hub
384  HB_HOUSTON   Trading Hub
385   HB_HUBAVG   Trading Hub
386    HB_NORTH   Trading Hub
387      HB_PAN   Trading Hub
388    HB_SOUTH   Trading Hub
389     HB_WEST   Trading Hub

In [15]:
# Return all the load zones
locations[locations["location_type"] == "Load Zone"]

       location location_type
515      LZ_AEN     Load Zone
516      LZ_CPS     Load Zone
517  LZ_HOUSTON     Load Zone
518     LZ_LCRA     Load Zone
519    LZ_NORTH     Load Zone
520    LZ_RAYBN     Load Zone
521    LZ_SOUTH     Load Zone
522     LZ_WEST     Load Zone

In [16]:
# Return all the DC ties
locations[locations["location_type"] == "Load Zone DC Tie"]

    location     location_type
214     DC_E  Load Zone DC Tie
215     DC_L  Load Zone DC Tie
216     DC_N  Load Zone DC Tie
217     DC_R  Load Zone DC Tie

There is a tremendous amount of data available for pricing in ERCOT, as well as other ISOs, with more being added all the time. Search the [Data Catalog](https://www.gridstatus.io/datasets?source=ercot) and select "ERCOT" in the Source dropdown for more.